### ISSUE TITLE
Clean up leftovers on close.

### ISSUE THREAD

**Issue by kajamin** [portapps/phyrox-portable#10]
firefox-portable-win64-70.0.1-30 
Windows 7 64bit.

Firefox keeps generating empty folders in AppData\Roaming, AppData\Local and AppData\LocalLow though it is supposed to run as a portable app. Have tried to remove the "Mozilla" folders manually, however, they were reproduced on the next start. Is it possible to do cleanup automatically on close? Or is there a possibility to prevent Firefox from generating those empty folders? Thank you!

**Comment by crazy-max** [comment]
Yes it is possible but we should first make sure that Firefox is not installed locally on the machine. In which case we would delete the local data.

**Comment by crazy-max** [comment]
@kajamin I've started to include this behavior for [Skype](https://github.com/portapps/skype-portable) and [WhatsApp](https://github.com/portapps/whatsapp-portable) through a new config parameter called `cleanup`. It will be available for Firefox on next release.

**Comment by kajamin** [comment]
> 
> 
> @kajamin I've started to include this behavior for [Skype](https://github.com/portapps/skype-portable) and [WhatsApp](https://github.com/portapps/whatsapp-portable) through a new config parameter called `cleanup`. It will be available for Firefox on next release.

Thank you for making it possible. Tested with the latest release and cleanup parameter was set to true.  The function does not seem to work proplerly. When I close firefox some leftover folders (e.g. AppData\Roaming\Mozilla\Firefox) are removed but not thouroughly. Empty mozilla folders remain even though I don't have any firefox installed locally.

**Comment by crazy-max** [comment]
@kajamin Cannot reproduce on my side. Please open a [bug report](https://github.com/portapps/phyrox-portable/issues/new?template=bug_report.md) and list the content of that folder please. Thanks.
