### ISSUE TITLE
Trademark Policy violation report

### ISSUE THREAD

**Issue by crazy-max** [portapps/phyrox-portable#11]
We have received a Trademark Policy violation report of @mozilla concerning this portapp:

> Hello,
> 
> I am an attorney for Mozilla Corporation and am writing to you about your Portapps project.
> 
> At Mozilla, we believe that free and open source software promotes the development of the Internet as a public resource, and that transparent community-based processes promote participation, accountability and trust. As such, we welcome developers building on our open source code.
> 
> At the same time, it is important that developers using our code comply with the relevant open source software licenses and do not use our trademarks in a way that might confuse users about the source of software. Firefox and Thunderbird are both released under the Mozilla Public License version 2.0 (MPLv2). Moreover, “Firefox” and “Thunderbird” are both registered Mozilla trademarks. The MPLv2 does not grant permission to use Mozilla trademarks.
> 
> Your Portapps project includes a number of apps released using Mozilla trademarks:
> 
> https://portapps.io/app/firefox-portable/  
> https://portapps.io/app/firefox-esr-portable/
> https://portapps.io/app/firefox-developer-portable/
> https://portapps.io/app/thunderbird-portable/
> 
> As your website explains, you make a number of modifications to the Mozilla-branded software that you distribute (see, e.g., “Modifications” and “Configuration” at https://portapps.io/app/firefox-portable/). Of course, open source software licenses allow for modified versions to be created and distributed. **But you cannot distribute modified versions of our software using Mozilla trademarks as the names of those modified products.**
> 
> For more details, Mozilla’s Trademark and Distribution policies are available online at:
> 
> https://www.mozilla.org/en-US/foundation/trademarks/policy/
> https://www.mozilla.org/en-US/foundation/trademarks/distribution-policy/ 
> 
> I would like to draw your attention to the following language from our policies:
> 
> _… if you make any changes to Firefox or other Mozilla software, you may not redistribute that product using any Mozilla trademark without Mozilla’s prior written consent and, typically, a distribution agreement with Mozilla. For example, you may not distribute a modified form of Firefox and continue to call it Firefox._
> 
> _…
> Don’t modify Mozilla’s trademarks, abbreviate them, or combine them with any other symbols, words, or images, or incorporate them into a tagline or slogan.
> ..._
> 
> _The specific license for each of Mozilla’s software products and code says what you can and cannot do with the code itself but does not give permission to use Mozilla’s trademarks. If you choose to build on or modify Mozilla’s open source code for your own project. … You Must: Choose branding, logos, and trademarks that denotes your own unique identity so as to clearly signal to users that there is no affiliation with or endorsement by Mozilla. …  You Must NOT: Use any Mozilla trademark in connection with the user-facing name or branding of your project._
> 
> Although you have included disclaimers on your website, that does not mean that you can use the "Firefox" and "Thunderbird" wordmarks and logos as the names and logos for your modified versions of our software. You may truthfully state, in words, that your software is based on Firefox and Thunderbird. **But you must use different names for your apps and use a different logo.**
> 
> You are also infringing Mozilla’s trademarked logos by modifying them and [combining them with your own logo](https://github.com/portapps/firefox-portable/blob/master/res/papp.png). You must remove these modified logos entirely from your website, apps, and GitHub repositories. For reference, you might review how the Firefox fork Pale Moon uses a different name and logo and thus avoids giving the impression it is an official Firefox product. You need to do a similar re-brand if you wish to continue distributing modified versions of Firefox.
> 
> It appears that users who install your modified version of Firefox see a dialogue box that looks like this:
> 
> ![image](https://user-images.githubusercontent.com/1951866/68329734-332de780-00d2-11ea-968b-6c709d92a4a4.png)
> 
> We assume that similar items are presented to users of your other Mozilla-based apps. 
> 
> In addition to the infringing altered "Firefox Portable" logo, this dialogue box raises two concerns. First, the copyright notice gives users the misleading impression that you authored all of Firefox Portable and not just the modifications you made. Second, the notice suggests that the Firefox Portable app is released under the MIT license. But most Firefox source code is released under the MPLv2 (which requires that modified versions of MPLv2 files also be released under the MPLv2 - see Section 3.1). When you do your rebrand, please also make sure you also change your install process so that users are not given misleading or inaccurate copyright and licensing information.
> 
> You might be aware of the [PortableApps project](https://portableapps.com/news/2019-10-28--firefox-portable-71.0-beta-4-released). Please note that the PortableApps.com developer has a written agreement with Mozilla Corporation and releases those apps using Firefox branding with Mozilla's express permission.
> 
> Mozilla always prefers to resolve disputes cooperatively. We are willing to give you 30 days to bring your software, websites, and repositories into compliance. Please respond by December 1, 2019 confirming that you have ceased infringing Mozilla trademarks and are in full compliance with the MPLv2.
> 
> Sincerely,
> Daniel Nazer
> Senior IP & Product Counsel
> Mozilla Corporation

**Comment by crazy-max** [comment]
Here is my response:

> Hello Daniel,
> 
> First of all, thank you for contacting me.
> 
> Being a user who appreciates your apps and prefers portable applications, I decided to create a wrapper with my Portapps project (https://portapps.io/) that allows to make your application portable.
> 
> As for the changes, I would like to point out that Firefox Portable, like all the applications on Portapps, do not undergo any modification, decompilation or hacking. Portapps only downloads your application, extracts it and compresses it with the wrapper written in Golang.
> This wrapper is developed and is completely dissociated from your product. "firefox-portable.exe" only runs "Firefox.exe" by adding environment variables, switches that make your application portable as most users could.
> 
> For transparency, every users can find the entire build process on TravisCI: https://travis-ci.com/portapps/firefox-portable
> My releases also have a checksum that is checked after this process to avoid any alteration.
> 
> As far as your Trademark Policy is concerned, it is true that I am completely at fault and I would like to apologize for that. I hope you understand that I am not trying to harm your product in any way.
> Concerning this dialog box of the setup, this notice only concerns the wrapper. But thanks for pointing this out, I will make modifications to clearly explain this notice.
> 
> I wanted to talk to you about PortableApps project because I had never noticed that the developer had this kind of agreement. So I wonder if Portapps could benefit from a similar agreement?
> I have already had this type of agreement for other applications such as Postman who gave me permission to use their product name and logo on Portapps. If it is possible for you it would be really great!
> 
> Once again, I apologize for any inconvenience this may have caused you.
> 
> I look forward to hearing from you,
> 
> CrazyMax

**Comment by crazy-max** [comment]
And their response:

> Hello Max,
> 
> Thanks for writing back. I asked our commercial & business development teams if they were interested in pursuing a licensing arrangement. They are not interested at this time. We only have limited resources for partnership and licensing agreements and can't pursue all opportunities.
> 
> We do appreciate that your version of "Firefox" has fairly limited modifications and doesn't appear to be malicious software. But even modest changes to preferences (such as whether "Know Your Rights" information is displayed to users) are sufficient to violate our policy against distributing modified versions of Mozilla software with our trademarks. Of course, end-users may choose to change preferences and settings in Firefox. But we don't allow others to distribute unofficial versions of "Firefox" with modified configurations or preferences.
> 
> So we do have to ask you to stop distributing software using Mozilla trademarks and logos. (You can refer to Firefox and Thunderbird in text when explaining that a product is based on them, but you can't use "Firefox" or "Thunderbird" as the name of the modified software you offer.)
> 
> Thanks,
> Daniel

**Comment by crazy-max** [comment]
So I will change the name and logo and it will look like:

* `firefox-portable => ffox-portable`
* `firefox-esr-portable => ffox-esr-portable`
* `firefox-developer-portable => ffox-developer-portable`
* `thunderbird-portable => tbird-portable`

**Comment by crazy-max** [comment]
Name and logo have been changed

**Comment by beppe9000** [comment]
I think the easy fix could be to define the portapps wrapper (or setup) as a tool used by the end user to perform the modifications, rather than a release of their """modified""" IP.

This would require the wrapper to perform all that on first run but should allow to distribute a "Portapps wrapper for Firefox" since you are not distributing firefox itself.

It would then be a similar to ninite, chocholatey or any other package manager.

**Comment by krystian3w** [comment]
Why no ban also portableapps.com? Have huge PAF.exe installers with offline Firefox code.
