### ISSUE TITLE
Phyrox portable creates a shortcut in start menu while running

### ISSUE THREAD

**Issue by SoulRipper888** [portapps/phyrox-portable#16]
Hello, while running Phyrox portable, the program creates a shortcut in my start menu.

1. Launch the Phyrox portable
2. Click on start menu
3. A shortcut is there: Phyrox portable. It points to [Phyrox portable folder]\app\firefox.exe

It disappears as soon as Phyrox portable is closed.

Configuration:
Phyrox v72.0.1-34 64 bits
Windows 7 Ultimate 64 bits

Thanks in advance for your help.
Best regards.

![smshortcut](https://user-images.githubusercontent.com/51204467/72207392-0cf14300-3499-11ea-864b-bb6c67fa6c06.png)
![shortcut_info](https://user-images.githubusercontent.com/51204467/72207393-0cf14300-3499-11ea-8b4a-92c0cd026099.png)

**Comment by crazy-max** [comment]
@tomasz1986 As stipulated on [Infos section](https://portapps.io/app/phyrox-portable/#infos) on phyrox-portable page, a shortcut is created at launch to allow native notifications and removed when Firefox is closed. On Windows, notifications are made through an [Application User Model ID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459(v=vs.85).aspx). A shortcut to the application must be added in the start menu to make desktop notifications working.

**Comment by crazy-max** [comment]
@SoulRipper888 As stipulated on [Infos section](https://portapps.io/app/phyrox-portable/#infos) on phyrox-portable page, a shortcut is created at launch to allow native notifications and removed when Firefox is closed. On Windows, notifications are made through an [Application User Model ID](https://msdn.microsoft.com/en-us/library/windows/desktop/dd378459(v=vs.85).aspx). A shortcut to the application must be added in the start menu to make desktop notifications working.
