### ISSUE TITLE
Please support customized policies.json

### ISSUE THREAD

**Issue by kaala** [portapps/phyrox-portable#25]
There are many policies can be setup using policies.json, about:policies#documentation
But phyrox portable always overwrite that file, and yaml cannot auto mapping those policies.

I prefer to disable DisableFirefoxAccounts, please allow us to keep the edited file

{
  "policies": {
    "DisableAppUpdate": false,
    "DisableFirefoxStudies": true,
    "DisableTelemetry": true,
    "DontCheckDefaultBrowser": true,
    "DisableFirefoxAccounts": true,
    "DisablePocket": true
  }
}

**Comment by crazy-max** [comment]
@kaala `DisableTelemetry` and `DisableFirefoxStudies` config entries have been removed but you can now use custom policies through `data/policies.json` file.
