### ISSUE TITLE
Does not allow 5 or more addons to be activated on startup

### ISSUE THREAD

**Issue by dbarev** [portapps/phyrox-portable#3]
### Behaviour

With latest version firefox-portable-win64-67.0.2-16 if 5 or more addons are installed, only the first 4 are activated on startup. That is it is possible to install multiple addons and they work fine after installation. Upon shut down of the application and new start only the first 4 are activated, the rest are listed as installed but are not activated. Any such add-on can be re-activated manually and will work fine until a restart of the application. Same behavior also in the ESR release.

#### Steps to reproduce this issue

1. Clean install firefox portable
2. Install any 4 addons randomly from the mozilla add-ons website
3. Shut down the app. Restart it. All addons work fine
4. Install any other add-ons so that total number of addons is more than 5 (6,10 or more)
5. Restart the app. The newly added add-ons are not working, they are not active. Manually opening about:addons and then disabling and enabling the said add-ons again will enable them until a restart of the application.

#### Expected behaviour

> Any number of installed add-ons should keep their enabled/disabled state upon restart of the app. If any add-on is enabled it should persist as enabled after app restart.

#### Actual behaviour

> See steps to reproduce

### Configuration

**App release: firefox-portable-win64-67.0.2-16** :

**Operating system: Windows 10 Pro 64 bits** :

**Winver screenshot** :

![image](https://user-images.githubusercontent.com/38895200/59606011-c44af480-9118-11e9-9239-3a282ae10b03.png)

### Screenshots

> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/38895200/59606099-f3f9fc80-9118-11e9-8c37-9057b4854e86.png)

### Logs

Join the log file `log\[appname]-portable.log` to this issue.
[firefox-portable.log](https://github.com/portapps/firefox-portable/files/3297060/firefox-portable.log)

**Comment by crazy-max** [comment]
@dbarev Thank you for this report, I will analyse this problem and come back to you.

**Comment by dbarev** [comment]
OK, I found a workaround that might be useful in actually resolving the bug. First when trying to reproduce the issue I found out that this bug occurs not only with 5 installed add-ons but also depending on the type of add-ons and the install sequence it could even turn up with 2-3 add-ons installed. The workaround is as follows:

1. First install all needed add-ons
2. Restart the app, some will be disabled and will not work -> this is how we reproduce the issue
3. Shut down the app, then go to the profile folder and delete the following files: addonStartup.json.lz4 and addonStartup.json.lz4.tmp (note: they will be recreated automatically on next start)
4. Restart the app, all add-ons will be disabled. Open about:addons and manually enable all add-ons. From this moment add-ons will be persistently enabled upon restarts

The above needs to be repeated upon installation of new add-ons.

**Comment by dbarev** [comment]
FYI: The bug is still there is the latest firefox-portable-win64-67.0.4-18 release

**Comment by crazy-max** [comment]
@dbarev I haven't dealt with the problem yet.

**Comment by crazy-max** [comment]
@dbarev Can you test [this release](https://github.com/portapps/firefox-portable/releases/tag/69.0-24)? Thanks!

**Comment by dbarev** [comment]
@crazy-max , this issue still persists with latest build 69.0.1 (64-bit).
The workaround is still possible but due to the change in the addons interface it is a real pain to do it manually ....

**Comment by crazy-max** [comment]
@dbarev Yes, the problem unfortunately persists.

**Comment by clemthi** [comment]
Hello,
I don't know if this helps but I've installed the version 70.0-29 on top of my "old" version 69.0.3-27 and I have 9 add-ons correctly running.

**Comment by dbarev** [comment]
@clemthi , you have to read the description of the bug carefully. Already installed and running addons are fine but try to install new ones and you will experience it.

**Comment by clemthi** [comment]
Hi @dbare, obviously my answer didn't help :)
I was more like providing another workaround.

**Comment by dbarev** [comment]
This is fixed in latest release 72.0.2

**Comment by crazy-max** [comment]
@dbarev Do you have a link to the changes made by Firefox about this?

**Comment by dbarev** [comment]
@crazy-max , not really, I am also not sure which build exactly fixed it, cause I jumped to the last one now but skipped some of the previous releases just after the renaming to phyrox. I have however identified a new bug - much more severe, will post it.
