### ISSUE TITLE
Auto Update is enabled.

### ISSUE THREAD

**Issue by KiNGKiMO** [portapps/phyrox-portable#41]
Hello,

Well, as title says.

I tried with latest phyrox version (80.0)

I also tried adding the command to data/policies.json with no success, looks like it's not even affected with policies.json at all.

Thank you so much.

**Comment by crazy-max** [comment]
Please create a proper [bug report](https://github.com/portapps/phyrox-portable/issues/new?template=bug_report.md). Also cannot reproduce your issue with current latest:

![image](https://user-images.githubusercontent.com/1951866/101410743-b3c3a680-38d7-11eb-9361-f5d977944764.png)
