### ISSUE TITLE
phyrox-portable.sample.yml crated/modified every time you start phyrox-portable.exe

### ISSUE THREAD

**Issue by z3huti** [portapps/phyrox-portable#53]
### Behaviour

phyrox-portable.sample.yml crated/modified every time you start phyrox-portable.exe even if there is alrady other phyrox-portable.yml

#### Steps to reproduce this issue

1.  crate phyrox-portable.yml
2.  detele phyrox-portable.sample.yml, or dont delete, it will will be overiten/modified anyway
3.  run phyrox-portable.exe

#### Expected behaviour

stop crating/modified  phyrox-portable.sample.yml at every portable.exe startup, if there is alrady one or if other yml file exists !!!!!!!

i gues that happpens with every portable app, not only firefox

**Comment by z3huti** [comment]
same for portapp-prev.json

do you realy have to write to that file same lines that already exists in that file?

**Comment by crazy-max** [comment]
@z3huti What's your issue about that? See also https://github.com/portapps/portapps/issues/62
