### ISSUE TITLE
Port to LibreWolf

### ISSUE THREAD

**Issue by ltGuillaume** [portapps/phyrox-portable#63]
[LibreWolf](https://gitlab.com/librewolf-community/browser/windows/)'s current `LibreWolf-Portable.exe` solution is broken: it's not actually portable, all its wrapper does is point to a profile folder within the main folder via the `-profile` argument (which evidently leads to issues with extensions when moving).

Would you be interested in adding a fork of phyrox-portable for LibreWolf to your portable apps collection?

**Comment by 3oheicrw** [comment]
You should post a request for a new portable app:

https://portapps.io/doc/request-app/
