### ISSUE TITLE
Update Firefox to 97.0

### ISSUE THREAD

**Issue by 3oheicrw** [portapps/phyrox-portable#64]
Firefox 97.0 released. LibreWolf also catched up to 97.0. Phyrox is currently lag behind at 96.0.3.

**Comment by crazy-max** [comment]
@3oheicrw As explained [on this page](https://portapps.io/doc/reporting-issue/), "We are aware of and notified of new application updates. So there’s no need to create an issue to update an application.". But feel free to open a PR.
