### ISSUE TITLE
Need to use personal portapps.cfg. for Privacy setting

### ISSUE THREAD

**Issue by znzazy** [portapps/phyrox-portable#84]
Firefox keeps remembering last Bookmark Folder 
so i want put this line "lockPref("browser.bookmarks.defaultLocation", "unfiled");" inside portapps.cfg
to resolve that

**Comment by crazy-max** [comment]
No need to have this in [`portapp.json` configuration](https://portapps.io/doc/configuration/), just change this in the browser directly at `about:config`:

![image](https://github.com/user-attachments/assets/153245dc-99e8-42f8-ac23-7334965198c2)
